# Generated by Django 5.1.4 on 2025-01-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='unit',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_of_buying',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moneyincome',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moneyincome',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reciept',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sell',
            name='unit',
            field=models.CharField(default='Kg', max_length=10),
        ),
    ]
