# Generated by Django 5.1.4 on 2025-01-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0002_remove_customer_unit_alter_customer_date_of_buying_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='unit',
        ),
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sell',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
